// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMKeUKHMErcIfi7llR-_ZY3riFekzez2E',
    appId: '1:856570783700:android:0c6cdd004564df5eaf1841',
    messagingSenderId: '856570783700',
    projectId: 'choonjang-sample-login',
    storageBucket: 'choonjang-sample-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMKeUKHMErcIfi7llR-_ZY3riFekzez2E',
    appId: '1:856570783700:ios:0ba05dce2ac835d2af1841',
    messagingSenderId: '856570783700',
    projectId: 'choonjang-sample-login',
    storageBucket: 'choonjang-sample-login.appspot.com',
    iosClientId: '856570783700-28mtcaov5b66fea21urk05vl2ivsgjmm.apps.googleusercontent.com',
    iosBundleId: 'com.choonjang.loginapp.loginApp',
  );
}
